name: CI

on: [workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        xcode: ["13.4.1", "14.1"]
    runs-on:  macos-12
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: ./other/download_libs.sh

      - name: Build
        run: xcodebuild -project iina.xcodeproj -scheme iina CODE_SIGNING_ALLOWED=NO
        env:
          DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer

      - name: Install dependencies
        run: tar czvf ${{ github.workspace }}/IINA.app.tar.gz /Users/runner/Library/Developer/Xcode/DerivedData/iina-*/Build/Products/Debug/IINA.app

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: IINA
          path: ${{ github.workspace }}/IINA.app.tar.gz

