name: CI

on: [workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        xcode: ["13.4.1", "14.1"]
    runs-on:  macos-12
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: ./other/download_libs.sh

      - name: Build
        run: xcodebuild -project iina.xcodeproj -scheme iina -config Release -archivePath ./archive archive
        env:
          DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer

      - name: Create tarball
        run: |
          rm -rf ./IINA.app
          mv ./archive.xcarchive/Products/Applications/IINA.app .
          otool -L ./IINA.app/Contents/MacOS/IINA
          tar czvf ${{ github.workspace }}/IINA.app.tar.gz ./IINA.app

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: IINA_${{ matrix.xcode }}
          path: ${{ github.workspace }}/IINA.app.tar.gz
